// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT4rpPSOxJD9-mgRrLeJZDoCWjr0tjGwo',
    appId: '1:407379155180:web:e3408b57f1855d0d556dc9',
    messagingSenderId: '407379155180',
    projectId: 'zia-project-68a74',
    authDomain: 'zia-project-68a74.firebaseapp.com',
    storageBucket: 'zia-project-68a74.firebasestorage.app',
    measurementId: 'G-7Z46GX55RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC37JzmLGEfNrMHHWL3KM_MK5tFj4W7TA8',
    appId: '1:407379155180:android:d74e6a406a4ae9a9556dc9',
    messagingSenderId: '407379155180',
    projectId: 'zia-project-68a74',
    storageBucket: 'zia-project-68a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQoF5-oB7SJgray-XkIb7CiMfEpvv4Aw',
    appId: '1:407379155180:ios:4833dc5bfbe4ecd7556dc9',
    messagingSenderId: '407379155180',
    projectId: 'zia-project-68a74',
    storageBucket: 'zia-project-68a74.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQoF5-oB7SJgray-XkIb7CiMfEpvv4Aw',
    appId: '1:407379155180:ios:4833dc5bfbe4ecd7556dc9',
    messagingSenderId: '407379155180',
    projectId: 'zia-project-68a74',
    storageBucket: 'zia-project-68a74.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT4rpPSOxJD9-mgRrLeJZDoCWjr0tjGwo',
    appId: '1:407379155180:web:b129660f3b591c68556dc9',
    messagingSenderId: '407379155180',
    projectId: 'zia-project-68a74',
    authDomain: 'zia-project-68a74.firebaseapp.com',
    storageBucket: 'zia-project-68a74.firebasestorage.app',
    measurementId: 'G-N61M3ZFTR7',
  );
}
